---
title: "Rap Lyric Sentiment Analysis"
author: "Anthony Baker"
date: "5/7/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(jsonlite)
library(DBI)
library(yaml)
library(tidytext)
library(lubridate)
```

```{r}
# Read from the DB
creds = read_yaml("db/genius_db.yml")
con <- dbConnect(RMariaDB::MariaDB(), 
                 username = creds$username,
                 password = creds$password,
                 host = creds$host,
                 dbname = creds$database)
dbListTables(con)

res <- dbSendQuery(con, "SELECT * FROM songs_v3")

songs <- dbFetch(res)
dbClearResult(res)
```

```{r}
# Inspect
future <- songs

# How many songs?
future %>%
  nrow()

# How many of the songs are Future's?
future %>% 
  filter(primary_artist_id == 2197) %>%
  nrow()

future %>% 
  pull(song_id) %>%
  anyDuplicated()

future %>% 
  count(lyrics_language, sort = T)

future %>% 
  count(published, sort = T)

```

```{r}
# Look at lyrics by line
future_lyrics <- future %>%
  # filter(song_id == 3304058) %>% 
  select(song_id, primary_artist_id, title, url, release_date, lyrics_language, lyrics) %>%
  mutate(release_date = as.Date(release_date),
         lyrics = str_replace(lyrics, '^\\["', ''), # Remove opening bracket in list
         lyrics = str_replace(lyrics, '\\"]$', ''), # Remove closing bracket in list
         lyrics = str_split(lyrics, '", "')) %>%
  unnest(lyrics) %>% 
  filter(lyrics != '') %>% # Don't include newlines
  # Create a verse artist column to distinguish who is rapping
  mutate(verse_artist = ifelse(str_detect(lyrics, '^\\[.*\\]$'), # Look for [Verse n: Artist]
                               lyrics,
                               NA),
         verse_artist = ifelse(str_detect(lyrics, ': '),
                               str_replace_all(verse_artist, '(^.*: )|(\\])', ''),
                               NA)) %>% # Isolate the artist name
  # Expand verse_artist for all relevant rows 
  fill(verse_artist) %>%
  # Exclude the verse signifiers
  filter(!str_detect(lyrics, '^\\[.*\\]$'))
```

```{r}
# Who are all the artists who contribute a verse in a song that Future is also on?
future_lyrics %>% 
  distinct(song_id, verse_artist) %>%
  count(verse_artist, sort = T) %>%
  View()
```

```{r}
# Look at lyrics by word
data(stop_words)

future_words <- future_lyrics %>% 
  unnest_tokens(word, lyrics) %>%
  anti_join(stop_words, by = "word")

top_words <- future_words %>%
  count(word, sort = T)

top_words %>%
  View()

# TODO: Fix character encodings
```

```{r}
# Words over time
all_months <- seq.Date(as.Date("2008-03-01"), as.Date("2018-04-01"), by = "month")
all_years <-  seq.Date(as.Date("2008-01-01"), as.Date("2018-01-01"), by = "year")

all_words <- future_words %>%
  distinct(word) %>%
  crossing(all_years) %>%
  rename(year = all_years)

future_words_over_time <- all_words %>%
  left_join(future_words %>%
              filter(!is.na(release_date)) %>%
              count(word, year = floor_date(release_date, "year")),
            by = c("word", "year")) %>%
  mutate(n = ifelse(is.na(n), 1, n), # To avoid NA/Inf errors
         previous_n = lag(n),
         change = (n - previous_n) / previous_n) %>%
  group_by(word) %>%
  mutate(mean_abs_change = mean(abs(change), na.rm = T)) %>%
  ungroup()

most_changed_words <- future_words_over_time %>%
  distinct(word, mean_abs_change) %>%
  top_n(20, wt = mean_abs_change)

future_words_over_time %>%
  inner_join(most_changed_words %>% select(word), by = "word") %>%
  View()

  
  arrange(month) %>% View()
  group_by(word) %>%
  mutate(change = (n - lag(n))/lag(n)) %>%
  ungroup() %>%
  View()

  

library(ggridges)

future_words %>%
  filter(!is.na(release_date),
         release_date >= "2009-01-01") %>%
  inner_join(top_words %>% 
               top_n(20, wt = n),
             by = "word") %>%
  mutate(month = floor_date(release_date, "month")) %>%
  # count(month = floor_date(release_date, "month"), word) %>%
  # ungroup() %>%
  ggplot(aes(month, word)) + 
  geom_density_ridges()

```

```{r}
# TODO: user the [Verse n: artist] tags to separate the verses
```

```{r}
songs %>%
  # TODO: Are lyric lines being split properly?
  mutate(lyrics = str_replace(lyrics, '^\\[', ''),
         lyrics = str_replace(lyrics, '\\]$', ''),
         # lyrics = str_replace_all(lyrics, '"', ''),
         lyrics = str_split(lyrics, '", "')) %>%
  unnest(lyrics) %>%
  View()
```

### Questions
0. Most frequent collaborators?
0A. Most frequent producers?
1. All time, most frequent words?
1A. Most frequent words over time?
1B. Most frequent words on his own songs vs guest verses?
2. Range of vocab?
3. Sentiment
4. Favorite drug?